### ISSUE TITLE
Specify (and test against) one or more versions of the GraphQL Spec

### ISSUE THREAD

**Issue by jkachmar** [hasura/graphql-parser-hs#89]
### TODO:

- [ ] Finish filling out this issue description

**Comment by abooij** [comment]
Downstream tracking bug here: hasura/graphql-engine#7901

**Comment by abooij** [comment]
(NB: `graphql-parser-hs` only implements the _syntax_ of GraphQL. Its type system is part of the HGE "parser framework".)

**Comment by jkachmar** [comment]
I obviously won’t be getting to any of these :)
